config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  namespace :api do
    namespace :v1 do
      root 'users#index'
      resources :users
      resources :sessions, only: [:create, :destroy]
      resources :confirmations, only: [:create]
      resources :stories, only: [:index, :create, :update, :destroy] do
        resources :scenes, only: [:index, :create, :update, :destroy] do
          put :update_order, on: :collection
        end

        resources :questions, only: [:index, :create, :update, :destroy] do
          put :update_order, on: :collection
        end

        post :clone, on: :member
      end

      resource :chart, only: [:show]
      resources :story_downloads, only: [:index, :create]
      resources :story_reads, only: [:create]
      resources :tags, only: [:index]
      resources :notifications, only: [:index, :create]
      resource :registered_tokens, only: [:update]
      resource :settings

      scope '/tags/:tag_id', as: :tags, module: 'tags' do
        resources :stories, only: [:index]
      end
    end
  end

  post 'create_user' => 'users#create', as: :create_user

  match 'download_web_guide', to: 'home#download_web_guide', via: :get
  match 'download_mobile_guide', to: 'home#download_mobile_guide', via: :get


  Sidekiq::Web.use Rack::Auth::Basic do |username, password|
    ActiveSupport::SecurityUtils.secure_compare(::Digest::SHA256.hexdigest(username), ::Digest::SHA256.hexdigest(ENV["SIDEKIQ_USERNAME"])) &
      ActiveSupport::SecurityUtils.secure_compare(::Digest::SHA256.hexdigest(password), ::Digest::SHA256.hexdigest(ENV["SIDEKIQ_PASSWORD"]))
  end if Rails.env.production?

  mount Sidekiq::Web, at: "/api/v1/sidekiq"
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container">
    <span class="navbar-brand mb-0 h1">Tiger</span>

    <div class="collapse navbar-collapse justify-content-end">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to 'Story', stories_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'User', users_path, class: 'nav-link' %>
        </li>
        <li class="nav-item dropdown">
          <% if user_signed_in? %>
            <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
              | <%= current_user.email %>
            </a>
          <% end %>
          <div class="dropdown-menu">
            <%= link_to 'Change password', edit_user_registration_path, class: 'dropdown-item' %>
            <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: 'dropdown-item' %>
          </div>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_messages.html.erb
<div class="row justify-content-md-center">
  <% flash.each do |key, value| %>
    <div class="col-5 alert alert-<%= alert_class_for(key) %>" role="alert">
      <a href="#" data-dismiss="alert" class="close">×</a>
      <ul>
        <li>
          <%= value %>
        </li>
      </ul>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html ng-app="Tiger">
  <head>
    <title>Tiger</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all' %>
  </head>

  <body ng-controller="MainCtrl">
    <%= render 'layouts/header' %>
    <div class="container">
      <ol class="breadcrumb">
        <%= render_breadcrumbs :tag => :li, :separator => " / " %>
      </ol>
      <ng-view></ng-view>

    </div>

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tiger</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <div class="container">
      <div class="row justify-content-md-center bg-white border-bottom box-shadow">
        <h2>Tiger</h2>
      </div>
      <%= render 'layouts/messages' %>
      <%= yield %>
    </div>
  </body>
</html>